name: CI Basico

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v6

      - name: Configurar Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.x"

      - name: Instalar dependencias
        run: bun install

      - name: Ejecutar linting
        run: bun run check

      - name: Ejecutar pruebas
        run: bun run test
